# Import NumPy

In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5,6,7,8,9]
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
arr=np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

# We can have one o more dimension in our array

In [5]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
# This is a list of list, but we only have a dimension to handle it
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
matriz = np.array(matriz)
# we have transformed the list of one dimesion to array of two dimensions
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexing

In [7]:
arr[0]

1

In [8]:
arr[1] + arr[2]

5

In [9]:
matriz[0]

array([1, 2, 3])

In [10]:
matriz[0,1]

2

# Slicing

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[0:2]

array([1, 2])

In [16]:
arr[0:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matriz[0]

array([1, 2, 3])

In [18]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])