In [1]:
import numpy as np

# Type of dimensions

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [4]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matriz= np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [6]:
tensor= np.array([[[8,9,0],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)
tensor.ndim

[[[8 9 0]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

## Add and Delete dimension

In [11]:
# you can define the nu of dimension when you declare the array
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [9]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [10]:
# you can expand the dimension even with existign arrays, Axis=0 refers to rows and Axis=1 refers to colums
expand = np.expand_dims(vector, axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

In [13]:
# you can substrack the dimension that aren't use
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
