In [11]:
import numpy as np

In [21]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [13]:
arr.dtype


dtype('int32')

# Data conversions

In [19]:
arr= np.array([1,2,3,4,5], dtype='float64')
arr.dtype

dtype('float64')

In [32]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [31]:
#float conversion
arr=arr.astype(np.float64)
arr

array([1., 2., 3., 4., 5.])

In [34]:
#bool conversion
arr=np.array([0,1,2,3,4,5])
arr=arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True])

In [36]:
#string conversion
arr=np.array([0,1,2,3,4,5])
arr=arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [37]:
#int conversion
arr=np.array(['0','1','2','3','4','5'])
arr=arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

# Note: We only can handle and manage arrays that have a same type of data